<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.0"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0"/>
        <PackageReference Include="NSubstitute" Version="5.1.0" />
        <PackageReference Include="NUnit" Version="3.14.0"/>
        <PackageReference Include="NUnit.Analyzers" Version="3.9.0"/>
        <PackageReference Include="NUnit3TestAdapter" Version="4.5.0"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Resources\" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Resources\26675_export.blueprint" />
      <EmbeddedResource Include="Resources\exploit_bp.json" />
      <None Update="dual.yaml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\TheIsland.Core\TheIsland.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Backend">
        <HintPath>..\TheIsland.Core\NQLibs\Backend.dll</HintPath>
      </Reference>
      <Reference Include="BotLib">
        <HintPath>..\TheIsland.Core\NQLibs\BotLib.dll</HintPath>
      </Reference>
      <Reference Include="NQutils">
        <HintPath>..\TheIsland.Core\NQLibs\NQutils.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
