<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<CodeAnalysisRuleSet>../theisland.ruleset</CodeAnalysisRuleSet>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UserSecretsId>dc81062e-ec17-4eb7-8ddf-2a4213878608</UserSecretsId>
		<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
		<RazorCompileOnBuild>true</RazorCompileOnBuild>
		<RazorCompileOnPublish>false</RazorCompileOnPublish>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<DocumentationFile>TheIsland.Website.xml</DocumentationFile>
		<Optimize>false</Optimize>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
		<WarningsAsErrors />
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DocumentationFile> TheIsland.Website.xml</DocumentationFile>
		<Optimize>true</Optimize>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<WarningsAsErrors />
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="dpk\**" />
	  <Content Remove="dpk\**" />
	  <EmbeddedResource Remove="dpk\**" />
	  <None Remove="dpk\**" />
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="../stylecop.json" Link="stylecop.json">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</AdditionalFiles>
	</ItemGroup>

	<ItemGroup>
		<AdditionalFiles Include="../theisland.ruleset" Link="theisland.ruleset">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</AdditionalFiles>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="AspNet.Security.OAuth.Discord" Version="8.2.0" />
		<PackageReference Include="AspNetCoreRateLimit" Version="5.0.0" />
		<PackageReference Include="AsyncFixer" Version="1.6.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="ConfigureAwaitChecker.Analyzer" Version="5.0.0.1">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Dapper" Version="2.1.35" />
		<PackageReference Include="Dapper.Contrib" Version="2.0.78" />
		<PackageReference Include="Hangfire.AspNetCore" Version="1.8.15" />
		<PackageReference Include="Hangfire.InMemory" Version="1.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="8.0.10" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="8.0.10" />
		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.21.0" />
		<PackageReference Include="Npgsql" Version="6.0.11" />
		<PackageReference Include="StackExchange.Exceptional.AspNetCore" Version="2.2.32" />
		<PackageReference Include="StackExchange.Exceptional.PostgreSql" Version="2.2.32" />
		<PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
	</ItemGroup>
	<ItemGroup>
	  <None Include="..\.editorconfig" Link=".editorconfig" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\TheIsland.Core\TheIsland.Core.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Content Update="Views\Store\FailedPurchase.cshtml">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	  <Content Update="websiteSettings.json">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>
	<ItemGroup>
	  <None Update="dual.yaml">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
