// <copyright file="DuBotConnector.cs" company="Paul Layne">
// Copyright (c) Paul Layne. All rights reserved.
// </copyright>
//<autogenerated />
namespace TheIsland.Core.Classes
{
    using System;
    using System.Linq;
    using System.Net.Http;
    using System.Threading.Tasks;
    using Backend;
    using Backend.Business;
    using BotLib.BotClient;
    using BotLib.Generated;
    using BotLib.Protocols;
    using BotLib.Protocols.Queuing;
    using Microsoft.Extensions.DependencyInjection;
    using NQ;
    using NQ.RDMS;
    using NQ.Router;
    using NQutils;
    using NQutils.Config;
    using NQutils.Logging;
    using NQutils.Sql;
    using Orleans;
    using TheIsland.Core.Settings;

    public interface IDUClient
    {
        Client Bot { get; }

        Task SendMessage(ulong who, string message);
    }

    public class DUClient : IDUClient
    {
        /// <summary>
        /// Gets rest Client.
        /// </summary>
        public static IDuClientFactory RestDuClientFactory => serviceProvider.GetRequiredService<IDuClientFactory>();

        /// <summary>
        /// Service Provider.
        /// </summary>
        protected static IServiceProvider serviceProvider;

        /// <summary>
        /// Orleans.
        /// </summary>
        protected static IClusterClient orleans;

        /// <summary>
        /// Data Accessor.
        /// </summary>
        protected static IDataAccessor dataAccessor;
        private readonly DualUniverseSettings _dualUniverseSettings;
        /// <summary>
        ///  Gets the bot itself.
        /// </summary>
        public Client Bot { get; }

        public DUClient(DualUniverseSettings settings)
        {
            Config.ReadYamlFile("mod", "./dual.yaml");
            this._dualUniverseSettings = settings;
            this.Setup().Wait();
            this.Bot = this.CreateUser(settings).GetAwaiter().GetResult();
        }

        /// <summary>
        /// Logins As Bot.
        /// </summary>
        /// <param name="settings"></param>
        /// <returns></returns>
        private Task<Client> CreateUser(DualUniverseSettings settings)
        {
            LoginInformations pi = LoginInformations.BotLogin(settings.IngameName, settings.BotUser, settings.BotPassword);
            return Client.FromFactory(RestDuClientFactory, pi, allowExising: true);
        }

        /// <summary>
        /// Configure the App.
        /// </summary>
        /// <returns></returns>
        private async Task Setup()
        {
            var services = new ServiceCollection();

            //services.RegisterCoreServices();
            var qurl = this._dualUniverseSettings.QueueingURL;

            if (string.IsNullOrEmpty(qurl))
            {
                qurl = "http://queueing:9630";
            }

            services
            .AddSingleton<ISql, Sql>()
            .AddInitializableSingleton<IGameplayBank, GameplayBank>()
            .AddSingleton<ILocalizationManager, LocalizationManager>()
            .AddTransient<IDataAccessor, DataAccessor>()
            .AddOrleansClient("IntegrationTests")
            .AddHttpClient()
            .AddTransient<NQutils.Stats.IStats, NQutils.Stats.FakeIStats>()
            .AddSingleton<IQueuing, RealQueuing>(sp => new RealQueuing(qurl, sp.GetRequiredService<IHttpClientFactory>().CreateClient()))
            .AddSingleton<IDuClientFactory, BotLib.Protocols.GrpcClient.DuClientFactory>();

            var sp = services.BuildServiceProvider();
            serviceProvider = sp;
            await serviceProvider.StartServices().ConfigureAwait(false);
            ClientExtensions.SetSingletons(sp);
            ClientExtensions.UseFactory(sp.GetRequiredService<IDuClientFactory>());
            orleans = serviceProvider.GetRequiredService<IClusterClient>();
            dataAccessor = serviceProvider.GetRequiredService<IDataAccessor>();
        }

        /// <summary>
        /// Simple Start Function
        /// </summary>
        /// <returns></returns>
        public async Task Start()
        {
            try
            {
                await this.Loop().ConfigureAwait(false);
            }
            catch (Exception e)
            {
                Console.WriteLine($"{e}\n{e.StackTrace}");
                throw;
            }
        }

        /// <summary>
        /// Loop Function.
        /// </summary>
        /// <returns></returns>
        public virtual Task Loop()
        {
            return Task.CompletedTask;
        }

        /// <summary>
        /// A Safe loop with a reconnect.
        /// </summary>
        /// <param name="action"></param>
        /// <param name="exceptionDelayMs"></param>
        /// <param name="reconnect"></param>
        /// <returns></returns>
        public async Task SafeLoop(Func<Task> action, int exceptionDelayMs, Func<Task> reconnect)
        {
            while (true)
            {
                try
                {
                    await action().ConfigureAwait(false);
                }
                catch (NQutils.Exceptions.BusinessException be) when (be.error.code == NQ.ErrorCode.InvalidSession)
                {
                    Console.WriteLine("reconnecting");
                    await reconnect().ConfigureAwait(false);
                    await Task.Delay(exceptionDelayMs).ConfigureAwait(false);
                }
                catch (Exception e)
                {
                    Console.WriteLine($"Exception in mod action: {e}\n{e.StackTrace}");
                    await Task.Delay(exceptionDelayMs).ConfigureAwait(false);
                }
            }
        }

        public async Task SendMessage(ulong who, string message)
        {
            await this.Bot.Req.ChatMessageSend(new NQ.MessageContent
            {
                channel = new NQ.MessageChannel
                {
                    channel = MessageChannelType.PRIVATE,
                    targetId = who,
                },
                message = message,
            });
        }
    }
}
